repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  -   id: check-yaml
  -   id: end-of-file-fixer
  -   id: trailing-whitespace
- repo: local
  hooks:
    - id: ruff
      name: Lint python files
      entry: ruff
      args: [
        "check",
        "--fix",
        ".",
      ]
      language: system
      types: [python]
    - id: ruff-format
      name: Format python files
      entry: ruff
      args: [
        "format",
        ".",
      ]
      language: system
      types: [python]
